//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int bank_id { get; set; }
        public string user_id { get; set; }
        public string acc_holder { get; set; }
        public Nullable<int> phone_no { get; set; }
        public Nullable<int> acc_no { get; set; }
        public Nullable<int> card_no { get; set; }
        public string acc_Type { get; set; }
        public Nullable<int> branch_no { get; set; }
        public Nullable<int> cvv { get; set; }
        public string exp_Date { get; set; }
        public string bank_Name { get; set; }
    }
}
