//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int hotel_id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<int> zip_code { get; set; }
        public string street_Address { get; set; }
        public string website { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> phone_no { get; set; }
        public string hotelMan_id { get; set; }
        public string Hotel_Name { get; set; }
    }
}
